### ISSUE TITLE
Cannot find 'lang_sorted_family' from 'generate_graphs_and_tables'

### ISSUE THREAD

**Issue by ErikaaWang** [copenlu/multilingual-typology-probing#1]
Hi, 
For the three files `01_neuron_overlap.py`, `02_lang_similarity_no_attr.py`, `03_genus_similarity.py` to generate the plots, they all have the import
```
from generate_graphs_and_tables import lang_sorted_family
```
However, I cannot find a package or script here named `generate_graphs_and_tables`. Could you please tell me where can I find this source? Thank you so much for your help :)

**Comment by ltorroba** [comment]
Hi! Sorry for the delay---could you try using this file and let us know if it works? https://gist.github.com/ltorroba/3d2ed2936b1244f3d57f162f3db33fca

**Comment by ErikaaWang** [comment]
Yes it works well! Thanks for your help and sorry for this late reply :)
